package Main;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.net.URI;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.Timer;
import javax.swing.filechooser.FileNameExtensionFilter;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Usuario1
 */
public class MainRun extends javax.swing.JFrame {
     private Timer t;
     private ActionListener ac;
     private int x = 0;
    /**
     * Creates new form Main
     */
    String nameCarpeta = "";
    public MainRun() {
        initComponents();
        this.setTitle("CREAR CARPETA");
        this.setLocationRelativeTo(null);
        this.setSize(580, 338);
        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        Btn_Copiar = new javax.swing.JButton();
        txtURLSAVE = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSearchJSON = new javax.swing.JButton();
        txtUrlJSON = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSearchIMG = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 4, 45));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setForeground(new java.awt.Color(255, 204, 0));
        jPanel1.setLayout(null);

        jButton1.setText("Organizar archivos");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(390, 250, 150, 30);

        Btn_Copiar.setForeground(new java.awt.Color(102, 51, 0));
        Btn_Copiar.setText("CREAR CARPETAS");
        Btn_Copiar.setToolTipText("");
        Btn_Copiar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        Btn_Copiar.setBorderPainted(false);
        Btn_Copiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Btn_Copiar.setFocusable(false);
        Btn_Copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CopiarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Copiar);
        Btn_Copiar.setBounds(180, 190, 160, 18);

        txtURLSAVE.setForeground(new java.awt.Color(102, 51, 0));
        txtURLSAVE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        txtURLSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLSAVEActionPerformed(evt);
            }
        });
        jPanel1.add(txtURLSAVE);
        txtURLSAVE.setBounds(20, 160, 480, 18);

        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("URL DONDE SE CREARÁN LAS CARPETAS");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 140, 440, 20);
        jLabel3.getAccessibleContext().setAccessibleName("URL DONDE SE GUARDARÁN LAS IMAGENES");

        btnSearchJSON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recurso 6.png"))); // NOI18N
        btnSearchJSON.setToolTipText("");
        btnSearchJSON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSearchJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchJSONActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchJSON);
        btnSearchJSON.setBounds(510, 110, 30, 22);

        txtUrlJSON.setForeground(new java.awt.Color(102, 51, 0));
        txtUrlJSON.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        jPanel1.add(txtUrlJSON);
        txtUrlJSON.setBounds(20, 110, 481, 18);

        jLabel1.setForeground(new java.awt.Color(102, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("URL DEL ARCHIVO JSON (Lista de claves)");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 90, 340, 20);

        jLabel6.setBackground(new java.awt.Color(102, 51, 0));
        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 51, 0));
        jLabel6.setText("Crear carpetas");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(240, 30, 190, 14);

        btnSearchIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Recurso 6.png"))); // NOI18N
        btnSearchIMG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 51, 0)));
        btnSearchIMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchIMGActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchIMG);
        btnSearchIMG.setBounds(510, 160, 30, 22);

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(255, 255, 0));
        jProgressBar1.setStringPainted(true);
        jPanel1.add(jProgressBar1);
        jProgressBar1.setBounds(140, 250, 230, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LINTERNA.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 248, 60, 22);

        jLabel5.setForeground(new java.awt.Color(51, 0, 0));
        jLabel5.setText("Link para convertir EXCEL a JSON");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(200, 50, 230, 20);

        jLabel7.setForeground(new java.awt.Color(204, 102, 0));
        jLabel7.setText("Creado por: Carlos Iván Pérez Perales y Juan José López Chávez.");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 280, 390, 16);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpiar.png"))); // NOI18N
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 20, 110, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_CopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CopiarActionPerformed
        String txtUrlJson = txtUrlJSON.getText();
        //String txtUrlImagenes = txtUrlImagen.getText();
        String txtUrlSave = txtURLSAVE.getText();
        //System.out.println("_"+txtUrlImagenes);
        if(txtUrlJson.isEmpty() || txtUrlSave.isEmpty()){
            JOptionPane optionPane = new JOptionPane("¡NO SE PERMITE QUE DEJES CAMPOS VACIOS, FAVOR DE LLENAR LOS CAMPOS!",JOptionPane.WARNING_MESSAGE);
            JDialog dialog = optionPane.createDialog("ADVERTENCIA"); 
            dialog.setAlwaysOnTop(true); // to show top of all other application dialog.setVisible(true); // to visible the dialog
            dialog.setVisible(true);
            //System.out.println("campos vacios");
        }
        else{
            try {
                // Selecciona el archivo
                    if(nameCarpeta.equals("Bienes inmuebles")){                       
                        JOptionPane.showMessageDialog(null, "No se crearon archivos porque no es el material correcto");
                    }else{
                        leerArchivoJSON(txtUrlJson, txtUrlSave);
                    }
                    
                   
                //printJson(txtUrlJson, txtUrlImagenes, txtUrlSave);

            } catch (IOException ex) {
                Logger.getLogger(MainRun.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(MainRun.class.getName()).log(Level.SEVERE, null, ex);
            }
       }
    }//GEN-LAST:event_Btn_CopiarActionPerformed

    private void btnSearchJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchJSONActionPerformed
        // CAPURAR UNA RUTA
        JFileChooser file = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("TEXT FILES", "json");
        file.setFileFilter(filter);
        int r = file.showOpenDialog(this);  
        //File fileName = file.getSelectedFile();
        if(r == JFileChooser.APPROVE_OPTION ){
           File archivo = file.getSelectedFile();
           txtUrlJSON.setText(archivo.toString());
        }     
    }//GEN-LAST:event_btnSearchJSONActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CopyPhotosFrame frame = new CopyPhotosFrame();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSearchIMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchIMGActionPerformed
         nameCarpeta = "";
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int r = file.showOpenDialog(this);  
        //File fileName = file.getSelectedFile();
        if(r == JFileChooser.APPROVE_OPTION ){
           File archivo = file.getSelectedFile();
            nameCarpeta = archivo.getName();
            switch(archivo.getName()){
                case "Cerámica":
                    txtURLSAVE.setText(archivo.toString());
                break;
                case "Estucos":
                    txtURLSAVE.setText(archivo.toString());
                break;
                case "Lítica":
                    txtURLSAVE.setText(archivo.toString());
                break;
                case "Malacología":
                    txtURLSAVE.setText(archivo.toString());
                break;
                case "Metales":
                    txtURLSAVE.setText(archivo.toString());
                break;
                case "Óseo":
                    txtURLSAVE.setText(archivo.toString());
                break;
               case "Bienes inmuebles":
                    txtURLSAVE.setText(archivo.toString());
                break;
                default:
                    JOptionPane.showMessageDialog(null, "Elige una carpeta válida: \n Cerámica \n Estucos \n Lítica \n Malacología \n Metales \n Óseo \n Bienes inmuebles");
            }
           
        }
    }//GEN-LAST:event_btnSearchIMGActionPerformed

    private void txtURLSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLSAVEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLSAVEActionPerformed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setForeground(Color.red);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        try{
            if(Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if(desktop.isSupported(Desktop.Action.BROWSE)){
                   desktop.browse(new URI("https://products.aspose.app/cells/es/conversion/excel-to-json"));
                }
            }
        }catch(Exception e){
            e.printStackTrace();
 
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        jLabel5.setForeground(Color.getHSBColor(51, 0, 0));
    }//GEN-LAST:event_jLabel5MouseExited
    
    public void moverImagenes(String IMG_ORIGEN,String IMGSave, String ID, String numFoto){
       String dirCarpeta = crearCarpeta(ID,IMGSave); //url de la carpeta a donde se guadan las fotos /Imagenes/T1_05202/"
        //C:\\Users\\Usuario1\\Documents\\NetBeansProjects\\PaulinaAndEdgarHack\\fotos\\
        Path origenPath = FileSystems.getDefault().getPath(IMG_ORIGEN+"\\"+numFoto);
        Path destinoPath = FileSystems.getDefault().getPath(dirCarpeta+"/"+numFoto);

        try {
            Files.copy(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            System.err.println(e);
        }
    }
    
    public String crearCarpeta(String Carpeta, String URLSave){
       // String Dest = System.getProperty("user.dir") + "/Imagenes/"+Carpeta; //------------------------------------------------------cambiar
        String Dest = URLSave+"/"+Carpeta;
        File directorio = new File(Dest);
        if(!directorio.exists()){
            if(directorio.mkdirs()){
              //directorio creado
                return Dest;
            }else{
            //ERRR AL CREAR EL DIRECTORIO - YA EXISTE 
                return null;
            }
        }
        return Dest;
    }
    
    public void leerArchivoJSON(String UrlJson, String URLSave) throws FileNotFoundException, IOException, ParseException{
        JSONParser parser = new JSONParser();
        FileReader reader = new FileReader(UrlJson);//t1.json
        Object obj = parser.parse(reader);//parseamos
        //leermos el primer array de mi json []
        //JSONObject JsonObj = (JSONObject) obj;
        JSONArray array = (JSONArray) obj;
        numeroArchivos(array, URLSave);
    }
    
    public void numeroArchivos(JSONArray array, String URLSave) throws IOException{
        //Crear objeto FileWriter que sera el que nos ayude a escribir sobre archivo
        Thread hilo = new Thread(){
            @Override
            public void run(){
                jProgressBar1.setMaximum(array.size());
                int counter = 0;
                for(int i = 0; i < array.size(); i++){

                    JSONObject ClaveJson = (JSONObject)array.get(i);
                    String claveExpedicion = (String) ClaveJson.get("Clave");
                    JSONObject cedulaAntariorJSON = (JSONObject)array.get(i);
                    String cedulaJSON = (String) cedulaAntariorJSON.get("Cédula anterior");
                    JSONObject catsaJSON = (JSONObject)array.get(i);
                    String CATSA = (String) catsaJSON.get("CATSA");

                    //CREAR LA CARPETA CON LA CLAVE DE EXCAVACIÓN. ESTO SE HACE UNA ÚNICA VEZ.
                    String carpetaPadre = crearCarpeta(claveExpedicion,URLSave);

                    //CREAR TODAS LAS CARPETAS

                    //SECCIÓN 1
                    String cedulaRegistro = crearCarpeta("Cédula de registro",carpetaPadre);
                    if(cedulaJSON != null){
                        String cedulaAnterior = crearCarpeta("Cédula anterior",cedulaRegistro);
                            crearCarpeta("Alta resolución",cedulaAnterior);
                            crearCarpeta("Baja resolución",cedulaAnterior);
                    }
                        String cedulaAutomatizada = crearCarpeta("Cédula automatizada",cedulaRegistro);
                            crearCarpeta("Cédula",cedulaAutomatizada);
                            crearCarpeta("Deterioros",cedulaAutomatizada);
                            crearCarpeta("Finales",cedulaAutomatizada);
                            crearCarpeta("Inicio",cedulaAutomatizada);
                            crearCarpeta("Procesos",cedulaAutomatizada);

                    if(CATSA != null){
                            crearCarpeta("Cédula CATSA",cedulaRegistro);

                    }  

                    //SECCIÓN 2
                    crearCarpeta("Etiqueta",carpetaPadre);

                    //SECCIÓN 3
                    String registroFotografico = crearCarpeta("Registro fotográfico",carpetaPadre);

                        crearCarpeta("Deterioros",registroFotografico);

                        crearCarpeta("Finales",registroFotografico);

                        crearCarpeta("Inicio",registroFotografico);

                        crearCarpeta("Procesos",registroFotografico);

                        crearCarpeta("Todas",registroFotografico);
                     //FIN DEL PROCESO DE CREAR TODAS LAS CARPETAS
                     jProgressBar1.setValue(counter);
                     counter ++;
                }
                jProgressBar1.setValue(counter+1);
                JOptionPane.showMessageDialog(null, "Se han creado las carpetas");
            }
        };hilo.start();
    }
    
    public void moverImagenCedula(String IMG_ORIGEN,String IMGSave, String numFoto){
       //String dirCarpeta = crearCarpeta(ID,IMGSave); //url de la carpeta a donde se guadan las fotos /Imagenes/T1_05202/"
        //C:\\Users\\Usuario1\\Documents\\NetBeansProjects\\PaulinaAndEdgarHack\\fotos\\
        Path origenPath = FileSystems.getDefault().getPath(IMG_ORIGEN+"\\"+numFoto);
        Path destinoPath = FileSystems.getDefault().getPath(IMGSave+"/"+numFoto);

        try {
            Files.copy(origenPath, destinoPath, StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException e) {
            System.err.println(e);
        }
    }
    
    public boolean existeFoto(String url){
        File archivo = new File(url);
        boolean foto;
        if (archivo.exists()) {
            if (archivo.isFile()) System.out.println("Es un archivo"); 
            if (archivo.isDirectory()) System.out.println("Es una carpeta");
            foto = true;
        }
        else {
            System.out.println("OJO: ¡¡No existe el archivo de configuración!!");
            foto = false;
        }
        return foto;
    }
    
    public void progressbar(int size, int i){
        Thread hilo = new Thread(){
            @Override
            public void run(){
           
                int sizeNew = size-1;
                int porcentaje = (i * sizeNew) / 100;
                jProgressBar1.setMaximum(size);
                jProgressBar1.setValue(porcentaje);
            }
        };hilo.start();
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Copiar;
    private javax.swing.JButton btnSearchIMG;
    private javax.swing.JButton btnSearchJSON;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField txtURLSAVE;
    private javax.swing.JTextField txtUrlJSON;
    // End of variables declaration//GEN-END:variables

}
